name: "serverPopulationStats"
description: "This plugin allows for measuremtn of the current number of players online in a systematic manner"
authors:
- "michu"
version: "1.0.6.9"
mainClass: "serverPopulationStats.Main"